namespace: cloudcostops

backend:
  replicaCount: 1

  image:
    repository: 483176634994.dkr.ecr.us-east-1.amazonaws.com/cloudcostops-backend
    tag: "bd580df4a63d0f6e599daa0a02af72af36feabed"

  service:
    port: 8000

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

frontend:
  replicaCount: 1

  image:
    repository: 483176634994.dkr.ecr.us-east-1.amazonaws.com/cloudcostops-frontend
    tag: "bd580df4a63d0f6e599daa0a02af72af36feabed"

  service:
    port: 3000

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi

postgres:
  image: postgres:16

  database: cloudcostops
  username: cloudcostops
  password: cloudcostops-dev-password

  service:
    port: 5432

  storage:
    size: 10Gi
    storageClass: gp2

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

ingress:
  enabled: true
  className: alb
  scheme: internet-facing
  targetType: ip