namespace: cloudcostops

backend:
  replicaCount: 1

  image:
    repository: 483176634994.dkr.ecr.us-east-1.amazonaws.com/cloudcostops-backend
    tag: "6ded1fb2a7fb874fe84441e7641003435df939da"

  service:
    port: 8000

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

frontend:
  replicaCount: 1

  image:
    repository: 483176634994.dkr.ecr.us-east-1.amazonaws.com/cloudcostops-frontend
    tag: "6ded1fb2a7fb874fe84441e7641003435df939da"

  service:
    port: 3000

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi

postgres:
  image: postgres:16

  database: cloudcostops
  username: cloudcostops
  password: cloudcostops-dev-password

  service:
    port: 5432

  storage:
    size: 10Gi
    storageClass: gp2

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

ingress:
  enabled: true
  className: alb
  scheme: internet-facing
  targetType: ip

  certificateArn: "arn:aws:acm:us-east-1:483176634994:certificate/15ef4ae4-1432-4e3d-b615-3925cd686c2b"
  sslRedirectPort: "443"