apiVersion: v1
kind: Secret
metadata:
  name: cloudcostops-backend-secret
  namespace: cloudcostops
type: Opaque
stringData:
  DATABASE_URL: postgresql://cloudcostops:cloudcostops-dev-password@cloudcostops-postgres:5432/cloudcostops