apiVersion: v1
kind: Service
metadata:
  name: cloudcostops-backend
  namespace: cloudcostops

spec:
  type: ClusterIP

  selector:
    app: cloudcostops-backend

  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP