apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloudcostops-postgres-pvc
  namespace: cloudcostops
spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: gp2

  resources:
    requests:
      storage: 10Gi