apiVersion: v1
kind: Secret
metadata:
  name: cloudcostops-postgres-secret
  namespace: cloudcostops
type: Opaque
stringData:
  POSTGRES_DB: cloudcostops
  POSTGRES_USER: cloudcostops
  POSTGRES_PASSWORD: cloudcostops-dev-password